GET http://localhost:3000/api/usuarios
user-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImNyZWF0ZWRBdCI6MTU5MjI0MzAwOSwiZXhwaXJlZEF0IjoxNTkyMjQzOTA5LCJpYXQiOjE1OTIyNDMwMDl9.SSbJp8HxMXxtAjIPzWA78w1ydT5oVXqeosUR8B_N0QI

###

GET http://streaming.zapto.org:3000/api/constructor/5

### mostrar constructor por id

GET http://170.253.49.245:3000/api/usuarios

### mostrar todos constructores

POST http://streaming.zapto.org:3000/api/constructor
Content-Type: application/json

{
    "nombre": "juanito",
    "apellido": "valderrama",
    "direccion": "calle marte"
}

### crear constructor

PUT http://streaming.zapto.org:3000/api/constructor/6

### editar constructor por id

DELETE http://streaming.zapto.org:3000/api/constructor/1

### eliminar un constructor por id




GET http://streaming.zapto.org:3000/api/noticias/1

### mostrar noticia

GET http://streaming.zapto.org:3000/api/noticias

### mostrar todas noticias

POST http://streaming.zapto.org:3000/api/noticias
Content-Type: application/json

{
    "titulo": "La mató por un yogurt",
    "texto": "Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas, las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.",
    "autor": "Mario Girón"
}

### crear noticia

PUT http://streaming.zapto.org:3000/api/noticia/1

### editar noticia por id


### mostrar todas noticias

POST http://localhost:3000/api/noticias
Content-Type: application/json
user-token: asdfasd

{
    "titulo": "La mató por un yogurt",
    "texto": "Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas, las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.",
    "autor": "Mario Girón"
}

###
POST http://streaming.zapto.org:3000/api/usuarios/login
Content-Type: application/json
user-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImNyZWF0ZWRBdCI6MTU5MjI0NDU0MiwiZXhwaXJlZEF0IjoxNTkyMjQ1NDQyLCJpYXQiOjE1OTIyNDQ1NDJ9.CYGZ22-si6sMMfg4tQ8JJo08Z5PQjaKu7Nv6p3qXvfY

{
    "email": "david",
    "password": "12345"
}